# Generated by Django 5.0.3 on 2024-04-05 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="mobile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="app.mobile",
            ),
        ),
    ]
